import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
// this page accessible at http://localhost:3000/

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          {/* 
            this link will navigate to the page without reloading the page
            this link didn't work as expected in nextjs 11 or 12
            to fix this issue i used legacyBehavior
            this link didn't make a reload of the page 
          */}
          {/* 
              mohamed is the folder name
              activities is the file name
          */}
          <Link href="mohamed/activities" legacyBehavior>
            <a>My Activities</a>
          </Link>
          <br />
          {/* 

              /mohamed is the folder name that render the index.tsx file automatically
          
          */}
          <Link href="/mohamed" legacyBehavior>
            <a>Mohamed Page</a>
          </Link>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
        </div>
      </main>
    </div>
  );
}
